# Generated by Django 4.0.5 on 2022-07-12 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_hand_active_player_hand_revealed_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit_trump', models.IntegerField(choices=[(1, 'Diamonds'), (2, 'Clubs'), (3, 'Hearts'), (4, 'Spades')], null=True)),
                ('suit_lead', models.IntegerField(choices=[(1, 'Diamonds'), (2, 'Clubs'), (3, 'Hearts'), (4, 'Spades')], null=True)),
                ('cards', models.ManyToManyField(to='game.card')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hand')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.player')),
            ],
        ),
    ]
