# Generated by Django 4.0.5 on 2022-07-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_trick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_one_points',
            new_name='team_black_points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_two_points',
            new_name='team_red_points',
        ),
        migrations.RenameField(
            model_name='trick',
            old_name='cards',
            new_name='played_cards',
        ),
        migrations.RenameField(
            model_name='trick',
            old_name='winner',
            new_name='player_winning',
        ),
        migrations.AddField(
            model_name='trick',
            name='card_winning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='winning_card', to='game.card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='suit',
            field=models.CharField(choices=[('D', 'Diamonds'), ('C', 'Clubs'), ('H', 'Hearts'), ('S', 'Spades')], max_length=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Ace'), (2, 'King'), (3, 'Queen'), (4, 'Jack'), (5, 'Ten'), (6, 'Nine')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('RED', 'Red'), ('BLK', 'Black')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trick',
            name='suit_lead',
            field=models.IntegerField(choices=[('D', 'Diamonds'), ('C', 'Clubs'), ('H', 'Hearts'), ('S', 'Spades')], null=True),
        ),
        migrations.AlterField(
            model_name='trick',
            name='suit_trump',
            field=models.IntegerField(choices=[('D', 'Diamonds'), ('C', 'Clubs'), ('H', 'Hearts'), ('S', 'Spades')], null=True),
        ),
    ]
