# Generated by Django 4.0.5 on 2022-07-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_player_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trick',
            old_name='played_cards',
            new_name='cards_played',
        ),
    ]
