# Generated by Django 4.0.6 on 2022-07-27 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0017_profile_losses_profile_wins'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'game', 'team', 'position')},
        ),
    ]
